apiVersion: apps/v1
kind: Deployment
metadata:
  name: HRSystem
  labels:
    app: HRSystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HRSystem
  template:
    metadata:
      labels:
        app: HRSystem
    spec:
      containers:
        - name: HRSystem
          image: username/HRSystem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5